import type { TarotCardDefinition } from "@/lib/tarot/types";

/** Rider-Waite-Smith style 78-card deck definitions. */
export const TAROT_DECK: TarotCardDefinition[] = [
  {
    id: "major-00",
    slug: "the-fool",
    nameEn: "The Fool",
    nameKo: "바보",
    arcana: "major",
    suit: null,
    number: 0,
    keywordsUpright: ["새 출발","자유","호기심"],
    keywordsReversed: ["무분별","준비 부족","경솔함"],
    shortMeaningUpright: "두려움보다 호기심을 택하면 작은 첫걸음이 길을 열어 줍니다.",
    shortMeaningReversed: "성급한 결정은 피하고, 기본을 점검한 뒤 천천히 시작하세요.",
    themes: ["시작","모험","가능성"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-01",
    slug: "the-magician",
    nameEn: "The Magician",
    nameKo: "마법사",
    arcana: "major",
    suit: null,
    number: 1,
    keywordsUpright: ["의지","집중","실행"],
    keywordsReversed: ["조작","속임","자신감 부족"],
    shortMeaningUpright: "이미 가진 재능과 자원을 연결하면 원하는 방향으로 움직일 수 있습니다.",
    shortMeaningReversed: "능력을 과장하지 말고, 솔직한 실행으로 신뢰를 쌓으세요.",
    themes: ["창조","의지","기술"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-02",
    slug: "the-high-priestess",
    nameEn: "The High Priestess",
    nameKo: "여사제",
    arcana: "major",
    suit: null,
    number: 2,
    keywordsUpright: ["직관","내면","침착"],
    keywordsReversed: ["불안","비밀","망설임"],
    shortMeaningUpright: "서두르지 않고 내면의 목소리를 들으면 답이 조용히 드러납니다.",
    shortMeaningReversed: "감정에 휘둘리기보다 사실과 감각을 차분히 구분해 보세요.",
    themes: ["직관","침묵","지혜"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-03",
    slug: "the-empress",
    nameEn: "The Empress",
    nameKo: "여황제",
    arcana: "major",
    suit: null,
    number: 3,
    keywordsUpright: ["풍요","돌봄","성장"],
    keywordsReversed: ["과잉","게으름","의존"],
    shortMeaningUpright: "스스로와 주변을 따뜻히 돌보면 관계와 일 모두 자연스럽게 자랍니다.",
    shortMeaningReversed: "베풂과 휴식의 균형을 맞추며, 과한 기대는 내려놓으세요.",
    themes: ["양육","풍요","창조"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-04",
    slug: "the-emperor",
    nameEn: "The Emperor",
    nameKo: "황제",
    arcana: "major",
    suit: null,
    number: 4,
    keywordsUpright: ["구조","책임","안정"],
    keywordsReversed: ["경직","통제","고집"],
    shortMeaningUpright: "명확한 기준과 책임 있는 결정이 혼란 속에서도 중심을 잡아 줍니다.",
    shortMeaningReversed: "지나친 통제보다 유연한 협의로 균형을 회복하세요.",
    themes: ["권위","질서","안정"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-05",
    slug: "the-hierophant",
    nameEn: "The Hierophant",
    nameKo: "교황",
    arcana: "major",
    suit: null,
    number: 5,
    keywordsUpright: ["전통","배움","가치"],
    keywordsReversed: ["틀에 박힘","형식","맹목"],
    shortMeaningUpright: "검증된 방법과 선배의 조언을 참고하면 실수를 줄일 수 있습니다.",
    shortMeaningReversed: "규칙에만 맞추지 말고, 내 상황에 맞게 해석해 적용하세요.",
    themes: ["교육","신념","공동체"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-06",
    slug: "the-lovers",
    nameEn: "The Lovers",
    nameKo: "연인",
    arcana: "major",
    suit: null,
    number: 6,
    keywordsUpright: ["선택","조화","진심"],
    keywordsReversed: ["갈등","유혹","불일치"],
    shortMeaningUpright: "가치관이 맞는 선택을 하면 관계와 일 모두 더 단단해집니다.",
    shortMeaningReversed: "타인의 기대보다 내 기준을 분명히 하고 대화로 오해를 풀어 보세요.",
    themes: ["사랑","선택","조화"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-07",
    slug: "the-chariot",
    nameEn: "The Chariot",
    nameKo: "전차",
    arcana: "major",
    suit: null,
    number: 7,
    keywordsUpright: ["전진","의지","승리"],
    keywordsReversed: ["조급","방향 상실","갈등"],
    shortMeaningUpright: "목표를 분명히 하고 한 걸음씩 밀어붙이면 흐름을 되찾을 수 있습니다.",
    shortMeaningReversed: "속도를 늦추고 우선순위를 정리하면 불필요한 충돌을 줄일 수 있습니다.",
    themes: ["의지","진행","통제"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-08",
    slug: "strength",
    nameEn: "Strength",
    nameKo: "힘",
    arcana: "major",
    suit: null,
    number: 8,
    keywordsUpright: ["용기","인내","온화한 힘"],
    keywordsReversed: ["불안","자기 의심","억압"],
    shortMeaningUpright: "부드러운 인내와 자신감이 어려운 상황을 차분히 풀어 줍니다.",
    shortMeaningReversed: "억지로 참기보다 감정을 인정하고, 작은 승리부터 쌓아 가세요.",
    themes: ["용기","인내","자기 수용"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-09",
    slug: "the-hermit",
    nameEn: "The Hermit",
    nameKo: "은둔자",
    arcana: "major",
    suit: null,
    number: 9,
    keywordsUpright: ["성찰","고독","탐색"],
    keywordsReversed: ["고립","회피","답답함"],
    shortMeaningUpright: "잠시 물러나 생각을 정리하면 다음 행동이 더 선명해집니다.",
    shortMeaningReversed: "혼자 끙끙대지 말고, 신뢰할 사람과 필요한 만큼 나눠 보세요.",
    themes: ["성찰","지혜","내면"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-10",
    slug: "wheel-of-fortune",
    nameEn: "Wheel of Fortune",
    nameKo: "운명의 수레바퀴",
    arcana: "major",
    suit: null,
    number: 10,
    keywordsUpright: ["변화","기회","순환"],
    keywordsReversed: ["불안정","운에 의존","저항"],
    shortMeaningUpright: "흐름이 바뀌는 시점이니 유연하게 대응하면 새 기회가 보입니다.",
    shortMeaningReversed: "통제할 수 없는 일에 매달리지 말고, 할 수 있는 준비에 집중하세요.",
    themes: ["변화","운명","순환"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-11",
    slug: "justice",
    nameEn: "Justice",
    nameKo: "정의",
    arcana: "major",
    suit: null,
    number: 11,
    keywordsUpright: ["공정","균형","책임"],
    keywordsReversed: ["편향","불공정","회피"],
    shortMeaningUpright: "사실에 근거한 공정한 판단이 장기적으로 마음을 편하게 합니다.",
    shortMeaningReversed: "감정적 결론을 멈추고, 증거와 기록을 차분히 확인해 보세요.",
    themes: ["공정","진실","균형"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-12",
    slug: "the-hanged-man",
    nameEn: "The Hanged Man",
    nameKo: "매달린 사람",
    arcana: "major",
    suit: null,
    number: 12,
    keywordsUpright: ["관점 전환","기다림","포기"],
    keywordsReversed: ["정체","희생 과다","답답함"],
    shortMeaningUpright: "잠시 멈춰 다른 각도에서 보면 막혔던 문제가 풀릴 수 있습니다.",
    shortMeaningReversed: "무의미한 기다림은 줄이고, 작은 실험으로 방향을 다시 잡으세요.",
    themes: ["관점","인내","깨달음"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-13",
    slug: "death",
    nameEn: "Death",
    nameKo: "죽음",
    arcana: "major",
    suit: null,
    number: 13,
    keywordsUpright: ["끝과 시작","전환","정리"],
    keywordsReversed: ["집착","두려움","정체"],
    shortMeaningUpright: "낡은 방식을 정리하면 비워진 자리에 더 맞는 변화가 들어옵니다.",
    shortMeaningReversed: "끝을 두려워하기보다, 지금 유지할 것과 놓을 것을 구분해 보세요.",
    themes: ["변화","전환","재탄생"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-14",
    slug: "temperance",
    nameEn: "Temperance",
    nameKo: "절제",
    arcana: "major",
    suit: null,
    number: 14,
    keywordsUpright: ["균형","조율","인내"],
    keywordsReversed: ["극단","불균형","조급함"],
    shortMeaningUpright: "서로 다른 요소를 조화롭게 섞으면 안정적인 결과를 얻을 수 있습니다.",
    shortMeaningReversed: "한쪽으로 치우친 선택을 줄이고, 중간 지점을 찾아 조율하세요.",
    themes: ["균형","조화","치유"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-15",
    slug: "the-devil",
    nameEn: "The Devil",
    nameKo: "악마",
    arcana: "major",
    suit: null,
    number: 15,
    keywordsUpright: ["욕망","집착","현실 직시"],
    keywordsReversed: ["해방","각성","경계"],
    shortMeaningUpright: "나를 묶는 습관과 두려움을 알아차리는 것만으로도 선택지가 넓어집니다.",
    shortMeaningReversed: "죄책감 대신 작은 변화부터 시도하며, 도움을 요청해도 괜찮습니다.",
    themes: ["집착","욕망","해방"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-16",
    slug: "the-tower",
    nameEn: "The Tower",
    nameKo: "탑",
    arcana: "major",
    suit: null,
    number: 16,
    keywordsUpright: ["충격","깨달음","해방"],
    keywordsReversed: ["회피","불안","저항"],
    shortMeaningUpright: "갑작스런 변화도 오래 쌓인 문제를 드러내 주니, 솔직히 대면해 보세요.",
    shortMeaningReversed: "붕괴를 두려워하기보다 안전망을 만들고 차분히 재정비하세요.",
    themes: ["파괴","각성","재건"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-17",
    slug: "the-star",
    nameEn: "The Star",
    nameKo: "별",
    arcana: "major",
    suit: null,
    number: 17,
    keywordsUpright: ["희망","치유","영감"],
    keywordsReversed: ["낙담","불신","지침"],
    shortMeaningUpright: "작은 희망을 붙잡고 꾸준히 나아가면 마음과 상황이 서서히 회복됩니다.",
    shortMeaningReversed: "완벽한 타이밍을 기다리기보다, 오늘 할 수 있는 돌봄부터 시작하세요.",
    themes: ["희망","치유","영감"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-18",
    slug: "the-moon",
    nameEn: "The Moon",
    nameKo: "달",
    arcana: "major",
    suit: null,
    number: 18,
    keywordsUpright: ["불확실","감정","직관"],
    keywordsReversed: ["혼란","오해","불안"],
    shortMeaningUpright: "모든 것이 분명하지 않아도, 감정을 기록하며 천천히 길을 찾을 수 있습니다.",
    shortMeaningReversed: "상상과 사실을 구분하고, 확인되지 않은 정보에 크게 흔들리지 마세요.",
    themes: ["무의식","직관","불확실"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-19",
    slug: "the-sun",
    nameEn: "The Sun",
    nameKo: "태양",
    arcana: "major",
    suit: null,
    number: 19,
    keywordsUpright: ["기쁨","성공","명료함"],
    keywordsReversed: ["과신","일시적 침체","기대 과다"],
    shortMeaningUpright: "솔직한 태도와 긍정적인 에너지가 주변과의 신뢰를 키워 줍니다.",
    shortMeaningReversed: "좋은 흐름도 겸손하게 점검하며, 무리한 낙관은 조절하세요.",
    themes: ["기쁨","성공","활력"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-20",
    slug: "judgement",
    nameEn: "Judgement",
    nameKo: "심판",
    arcana: "major",
    suit: null,
    number: 20,
    keywordsUpright: ["각성","평가","재시작"],
    keywordsReversed: ["자기비난","후회","미루기"],
    shortMeaningUpright: "지난 경험을 바탕으로 솔직히 돌아보면 더 성숙한 재출발이 가능합니다.",
    shortMeaningReversed: "과거에 매이지 말고, 지금 할 수 있는 책임 있는 한 걸음을 택하세요.",
    themes: ["각성","용서","재탄생"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "major-21",
    slug: "the-world",
    nameEn: "The World",
    nameKo: "세계",
    arcana: "major",
    suit: null,
    number: 21,
    keywordsUpright: ["완성","통합","성취"],
    keywordsReversed: ["미완","정체","마무리 지연"],
    shortMeaningUpright: "한 단계를 마무리하고 다음 목표로 넘어갈 준비가 되었음을 알려 줍니다.",
    shortMeaningReversed: "완벽을 기다리기보다 충분히 잘한 부분을 인정하고 다음을 설계하세요.",
    themes: ["완성","통합","성취"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "wands-01",
    slug: "ace-of-wands",
    nameEn: "Ace of Wands",
    nameKo: "완드 에이스",
    arcana: "minor",
    suit: "wands",
    number: 1,
    keywordsUpright: ["영감","시작","가능성"],
    keywordsReversed: ["지연","의욕 저하","방향 혼란"],
    shortMeaningUpright: "작은 불꽃 같은 아이디어를 실행에 옮기면 흐름이 살아납니다.",
    shortMeaningReversed: "에너지가 분산될 때는 하나에 집중해 불을 다시 지펴 보세요.",
    themes: ["열정","행동","창의"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "wands-02",
    slug: "two-of-wands",
    nameEn: "Two of Wands",
    nameKo: "완드 2",
    arcana: "minor",
    suit: "wands",
    number: 2,
    keywordsUpright: ["계획","결정","전망"],
    keywordsReversed: ["우유부단","두려움","정체"],
    shortMeaningUpright: "미래를 그리며 선택지를 비교하면 더 나은 방향을 고를 수 있습니다.",
    shortMeaningReversed: "완벽한 계획을 기다리기보다 작은 시도로 방향을 확인하세요.",
    themes: ["열정","행동","창의"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "wands-03",
    slug: "three-of-wands",
    nameEn: "Three of Wands",
    nameKo: "완드 3",
    arcana: "minor",
    suit: "wands",
    number: 3,
    keywordsUpright: ["확장","협력","진행"],
    keywordsReversed: ["지연","장애","조급함"],
    shortMeaningUpright: "이미 시작한 일에 사람과 자원을 더하면 성과가 커질 수 있습니다.",
    shortMeaningReversed: "기대와 현실의 간극을 점검하며, 병목을 하나씩 해결하세요.",
    themes: ["열정","행동","창의"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "wands-04",
    slug: "four-of-wands",
    nameEn: "Four of Wands",
    nameKo: "완드 4",
    arcana: "minor",
    suit: "wands",
    number: 4,
    keywordsUpright: ["축하","안정","기반"],
    keywordsReversed: ["불안","정체","외로움"],
    shortMeaningUpright: "지금의 성과를 인정하고 잠시 쉬면 다음 도약을 위한 힘이 됩니다.",
    shortMeaningReversed: "안주에 머물기보다 작은 새 목표를 세워 활력을 회복하세요.",
    themes: ["열정","행동","창의"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "wands-05",
    slug: "five-of-wands",
    nameEn: "Five of Wands",
    nameKo: "완드 5",
    arcana: "minor",
    suit: "wands",
    number: 5,
    keywordsUpright: ["경쟁","마찰","도전"],
    keywordsReversed: ["갈등 완화","타협","회피"],
    shortMeaningUpright: "의견 차이 속에서도 목표를 분명히 하면 건설적인 경쟁이 됩니다.",
    shortMeaningReversed: "불필요한 대립은 줄이고, 공통점을 찾아 협력을 시도해 보세요.",
    themes: ["열정","행동","창의"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "wands-06",
    slug: "six-of-wands",
    nameEn: "Six of Wands",
    nameKo: "완드 6",
    arcana: "minor",
    suit: "wands",
    number: 6,
    keywordsUpright: ["인정","승리","자신감"],
    keywordsReversed: ["자만","기대 불일치","지연"],
    shortMeaningUpright: "노력이 드러나는 시기이니 겸손하게 성과를 나누면 신뢰가 깊어집니다.",
    shortMeaningReversed: "타인의 평가에 얽매이지 말고, 내 기준으로 다음 목표를 세우세요.",
    themes: ["열정","행동","창의"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "wands-07",
    slug: "seven-of-wands",
    nameEn: "Seven of Wands",
    nameKo: "완드 7",
    arcana: "minor",
    suit: "wands",
    number: 7,
    keywordsUpright: ["방어","인내","용기"],
    keywordsReversed: ["압도","의심","포기"],
    shortMeaningUpright: "어려움 속에서도 자신의 입장을 지키면 결국 흐름이 바뀔 수 있습니다.",
    shortMeaningReversed: "모든 것을 혼자 막으려 하지 말고, 도움과 전략을 함께 쓰세요.",
    themes: ["열정","행동","창의"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "wands-08",
    slug: "eight-of-wands",
    nameEn: "Eight of Wands",
    nameKo: "완드 8",
    arcana: "minor",
    suit: "wands",
    number: 8,
    keywordsUpright: ["속도","소식","진행"],
    keywordsReversed: ["조급","지연","산만"],
    shortMeaningUpright: "빠르게 움직일 때이니 우선순위를 정해 효율적으로 처리하세요.",
    shortMeaningReversed: "속도만 내세우지 말고, 중요한 부분을 다시 한번 확인하세요.",
    themes: ["열정","행동","창의"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "wands-09",
    slug: "nine-of-wands",
    nameEn: "Nine of Wands",
    nameKo: "완드 9",
    arcana: "minor",
    suit: "wands",
    number: 9,
    keywordsUpright: ["끈기","경계","준비"],
    keywordsReversed: ["피로","방어적","불안"],
    shortMeaningUpright: "거의 다 왔으니 마지막까지 차분히 지키면 원하는 결과에 가까워집니다.",
    shortMeaningReversed: "혼자 버티기 지치면 휴식과 위임으로 에너지를 회복하세요.",
    themes: ["열정","행동","창의"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "wands-10",
    slug: "ten-of-wands",
    nameEn: "Ten of Wands",
    nameKo: "완드 10",
    arcana: "minor",
    suit: "wands",
    number: 10,
    keywordsUpright: ["부담","책임","성취"],
    keywordsReversed: ["과로","조직","해제"],
    shortMeaningUpright: "많은 일을 감당 중이라면 역할을 나누고 우선순위를 재정리하세요.",
    shortMeaningReversed: "모든 책임을 혼자 지지 말고, 필요한 것만 남기고 위임하세요.",
    themes: ["열정","행동","창의"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "wands-11",
    slug: "page-of-wands",
    nameEn: "Page of Wands",
    nameKo: "완드 시종",
    arcana: "minor",
    suit: "wands",
    number: 11,
    keywordsUpright: ["호기심","학습","열정"],
    keywordsReversed: ["미숙","산만","경솔"],
    shortMeaningUpright: "새로운 시도에 대한 순수한 관심이 실력과 기회를 키워 줍니다.",
    shortMeaningReversed: "끝까지 배우는 태도를 유지하며, 기초부터 차근차근 쌓으세요.",
    themes: ["열정","행동","창의"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "wands-12",
    slug: "knight-of-wands",
    nameEn: "Knight of Wands",
    nameKo: "완드 기사",
    arcana: "minor",
    suit: "wands",
    number: 12,
    keywordsUpright: ["행동","모험","추진"],
    keywordsReversed: ["충동","조급","산만"],
    shortMeaningUpright: "과감한 실행이 필요한 때이니 목표를 분명히 하고 나아가세요.",
    shortMeaningReversed: "속도를 조절하고 주변 상황을 살피며 무리한 도약은 피하세요.",
    themes: ["열정","행동","창의"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "wands-13",
    slug: "queen-of-wands",
    nameEn: "Queen of Wands",
    nameKo: "완드 여왕",
    arcana: "minor",
    suit: "wands",
    number: 13,
    keywordsUpright: ["자신감","카리스마","따뜻한 리더십"],
    keywordsReversed: ["불안","질투","의존"],
    shortMeaningUpright: "온기와 확신으로 이끌면 주변도 자연스럽게 함께할 수 있습니다.",
    shortMeaningReversed: "타인의 반응에 흔들리지 말고, 스스로의 가치를 차분히 지키세요.",
    themes: ["열정","행동","창의"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "wands-14",
    slug: "king-of-wands",
    nameEn: "King of Wands",
    nameKo: "완드 왕",
    arcana: "minor",
    suit: "wands",
    number: 14,
    keywordsUpright: ["비전","리더십","경험"],
    keywordsReversed: ["독단","고집","압박"],
    shortMeaningUpright: "큰 그림을 제시하고 책임지면 팀과 프로젝트가 안정적으로 성장합니다.",
    shortMeaningReversed: "한 방향만 고집하지 말고, 현장의 목소리를 듣고 조율하세요.",
    themes: ["열정","행동","창의"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "cups-01",
    slug: "ace-of-cups",
    nameEn: "Ace of Cups",
    nameKo: "컵 에이스",
    arcana: "minor",
    suit: "cups",
    number: 1,
    keywordsUpright: ["새 감정","열림","직관"],
    keywordsReversed: ["감정 폐쇄","공허","회피"],
    shortMeaningUpright: "마음을 열면 따뜻한 관계나 창의적 영감이 자연스럽게 들어옵니다.",
    shortMeaningReversed: "상처를 숨기기보다 천천히 신뢰할 사람과 감정을 나눠 보세요.",
    themes: ["감정","관계","직관"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "cups-02",
    slug: "two-of-cups",
    nameEn: "Two of Cups",
    nameKo: "컵 2",
    arcana: "minor",
    suit: "cups",
    number: 2,
    keywordsUpright: ["연결","조화","파트너십"],
    keywordsReversed: ["불균형","오해","거리"],
    shortMeaningUpright: "서로의 마음을 존중하는 대화가 관계를 더 깊게 만들어 줍니다.",
    shortMeaningReversed: "기대치 차이를 솔직히 말하고, 작은 배려부터 회복하세요.",
    themes: ["감정","관계","직관"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "cups-03",
    slug: "three-of-cups",
    nameEn: "Three of Cups",
    nameKo: "컵 3",
    arcana: "minor",
    suit: "cups",
    number: 3,
    keywordsUpright: ["기쁨","우정","축하"],
    keywordsReversed: ["과잉","유희","피상"],
    shortMeaningUpright: "가까운 사람들과 함께하는 시간이 마음의 여유와 힘을 줍니다.",
    shortMeaningReversed: "즐거움에만 기대지 말고, 관계의 진심도 함께 돌아보세요.",
    themes: ["감정","관계","직관"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "cups-04",
    slug: "four-of-cups",
    nameEn: "Four of Cups",
    nameKo: "컵 4",
    arcana: "minor",
    suit: "cups",
    number: 4,
    keywordsUpright: ["권태","성찰","선택"],
    keywordsReversed: ["새 기회","만족","각성"],
    shortMeaningUpright: "잠시 멈춰 무엇이 진짜 만족스러운지 돌아보면 길이 보입니다.",
    shortMeaningReversed: "지나친 불만 대신, 이미 주어진 작은 기쁨에 감사해 보세요.",
    themes: ["감정","관계","직관"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "cups-05",
    slug: "five-of-cups",
    nameEn: "Five of Cups",
    nameKo: "컵 5",
    arcana: "minor",
    suit: "cups",
    number: 5,
    keywordsUpright: ["상실","아쉬움","슬픔"],
    keywordsReversed: ["회복","희망","지지"],
    shortMeaningUpright: "아쉬움을 인정하고 슬픔을 다루면 마음이 조금씩 가벼워집니다.",
    shortMeaningReversed: "남아 있는 지지와 가능성에 눈을 돌리며, 도움을 받아들이세요.",
    themes: ["감정","관계","직관"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "cups-06",
    slug: "six-of-cups",
    nameEn: "Six of Cups",
    nameKo: "컵 6",
    arcana: "minor",
    suit: "cups",
    number: 6,
    keywordsUpright: ["추억","순수","따뜻함"],
    keywordsReversed: ["과거 집착","미화","정체"],
    shortMeaningUpright: "좋은 기억에서 힘을 얻어 현재 관계를 더 따뜻하게 가꿀 수 있습니다.",
    shortMeaningReversed: "과거에 머물지 말고, 지금 만날 수 있는 사람에게 마음을 두세요.",
    themes: ["감정","관계","직관"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "cups-07",
    slug: "seven-of-cups",
    nameEn: "Seven of Cups",
    nameKo: "컵 7",
    arcana: "minor",
    suit: "cups",
    number: 7,
    keywordsUpright: ["선택","환상","가능성"],
    keywordsReversed: ["명료함","현실","결정"],
    shortMeaningUpright: "여러 감정과 선택지를 차분히 비교하면 진심이 드러납니다.",
    shortMeaningReversed: "모든 가능성을 쫓지 말고, 현실적인 하나를 골라 실행하세요.",
    themes: ["감정","관계","직관"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "cups-08",
    slug: "eight-of-cups",
    nameEn: "Eight of Cups",
    nameKo: "컵 8",
    arcana: "minor",
    suit: "cups",
    number: 8,
    keywordsUpright: ["떠남","탐색","성장"],
    keywordsReversed: ["회피","미완","불안"],
    shortMeaningUpright: "익숙함을 벗어나면 더 맞는 관계와 감정의 방향을 찾을 수 있습니다.",
    shortMeaningReversed: "도망이 아닌 성장인지 스스로에게 묻고, 필요한 마무리를 하세요.",
    themes: ["감정","관계","직관"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "cups-09",
    slug: "nine-of-cups",
    nameEn: "Nine of Cups",
    nameKo: "컵 9",
    arcana: "minor",
    suit: "cups",
    number: 9,
    keywordsUpright: ["만족","소원","안정"],
    keywordsReversed: ["과잉","방심","공허"],
    shortMeaningUpright: "마음의 평화를 누리며 감사하면 관계도 더 풍요로워집니다.",
    shortMeaningReversed: "지나친 안주를 경계하고, 감정의 균형을 꾸준히 돌보세요.",
    themes: ["감정","관계","직관"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "cups-10",
    slug: "ten-of-cups",
    nameEn: "Ten of Cups",
    nameKo: "컵 10",
    arcana: "minor",
    suit: "cups",
    number: 10,
    keywordsUpright: ["가족","조화","행복"],
    keywordsReversed: ["갈등","불화","기대"],
    shortMeaningUpright: "사랑하는 사람과의 유대가 든든한 기반이 되어 줍니다.",
    shortMeaningReversed: "완벽한 화합을 강요하지 말고, 대화로 차이를 부드럽게 풀세요.",
    themes: ["감정","관계","직관"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "cups-11",
    slug: "page-of-cups",
    nameEn: "Page of Cups",
    nameKo: "컵 시종",
    arcana: "minor",
    suit: "cups",
    number: 11,
    keywordsUpright: ["순수","직관","메시지"],
    keywordsReversed: ["미숙","감정 기복","환상"],
    shortMeaningUpright: "섬세한 감수성이 관계의 작은 신호를 읽는 데 도움이 됩니다.",
    shortMeaningReversed: "감정에만 기대지 말고, 사실 확인과 표현 연습을 병행하세요.",
    themes: ["감정","관계","직관"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "cups-12",
    slug: "knight-of-cups",
    nameEn: "Knight of Cups",
    nameKo: "컵 기사",
    arcana: "minor",
    suit: "cups",
    number: 12,
    keywordsUpright: ["로맨스","이상","매력"],
    keywordsReversed: ["비현실","변덕","회피"],
    shortMeaningUpright: "따뜻한 마음으로 다가가면 관계에 새로운 설렘이 생길 수 있습니다.",
    shortMeaningReversed: "이상만 쫓지 말고, 상대와의 현실적인 약속을 함께 세우세요.",
    themes: ["감정","관계","직관"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "cups-13",
    slug: "queen-of-cups",
    nameEn: "Queen of Cups",
    nameKo: "컵 여왕",
    arcana: "minor",
    suit: "cups",
    number: 13,
    keywordsUpright: ["공감","돌봄","직관"],
    keywordsReversed: ["감정 소모","경계","불안"],
    shortMeaningUpright: "깊은 공감과 배려가 주변에게 안정감과 치유를 줍니다.",
    shortMeaningReversed: "타인의 감정까지 떠안지 말고, 자신의 경계도 지켜 주세요.",
    themes: ["감정","관계","직관"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "cups-14",
    slug: "king-of-cups",
    nameEn: "King of Cups",
    nameKo: "컵 왕",
    arcana: "minor",
    suit: "cups",
    number: 14,
    keywordsUpright: ["성숙","균형","지혜"],
    keywordsReversed: ["냉정","억압","거리"],
    shortMeaningUpright: "감정을 차분히 다루는 성숙함이 관계를 오래 지탱해 줍니다.",
    shortMeaningReversed: "지나친 절제보다 솔직한 표현으로 따뜻함을 전해 보세요.",
    themes: ["감정","관계","직관"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "swords-01",
    slug: "ace-of-swords",
    nameEn: "Ace of Swords",
    nameKo: "검 에이스",
    arcana: "minor",
    suit: "swords",
    number: 1,
    keywordsUpright: ["명료함","진실","돌파"],
    keywordsReversed: ["혼란","오해","망설임"],
    shortMeaningUpright: "사실을 분명히 보면 막혔던 문제의 핵심이 드러납니다.",
    shortMeaningReversed: "성급한 결론은 피하고, 정보를 더 모은 뒤 판단하세요.",
    themes: ["사고","결정","갈등"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "swords-02",
    slug: "two-of-swords",
    nameEn: "Two of Swords",
    nameKo: "검 2",
    arcana: "minor",
    suit: "swords",
    number: 2,
    keywordsUpright: ["균형","선택","휴식"],
    keywordsReversed: ["결정 회피","긴장","정보 과잉"],
    shortMeaningUpright: "잠시 멈춰 양쪽을 비교하면 마음이 편해지는 선택을 할 수 있습니다.",
    shortMeaningReversed: "미루기만 하면 불안이 커지니, 작은 결정부터 내려 보세요.",
    themes: ["사고","결정","갈등"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "swords-03",
    slug: "three-of-swords",
    nameEn: "Three of Swords",
    nameKo: "검 3",
    arcana: "minor",
    suit: "swords",
    number: 3,
    keywordsUpright: ["슬픔","상처","분리"],
    keywordsReversed: ["치유","용서","회복"],
    shortMeaningUpright: "아픔을 인정하고 표현하면 마음이 서서히 회복될 수 있습니다.",
    shortMeaningReversed: "과거의 상처에 매이지 말고, 지금 가능한 치유에 집중하세요.",
    themes: ["사고","결정","갈등"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "swords-04",
    slug: "four-of-swords",
    nameEn: "Four of Swords",
    nameKo: "검 4",
    arcana: "minor",
    suit: "swords",
    number: 4,
    keywordsUpright: ["휴식","회복","고요"],
    keywordsReversed: ["고립","정체","불안"],
    shortMeaningUpright: "잠시 쉬며 생각을 정리하면 다음 행동이 더 선명해집니다.",
    shortMeaningReversed: "혼자만의 시간이 길어지면, 신뢰할 사람과 가볍게 연결하세요.",
    themes: ["사고","결정","갈등"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "swords-05",
    slug: "five-of-swords",
    nameEn: "Five of Swords",
    nameKo: "검 5",
    arcana: "minor",
    suit: "swords",
    number: 5,
    keywordsUpright: ["갈등","패배","긴장"],
    keywordsReversed: ["화해","교훈","양보"],
    shortMeaningUpright: "이긴다고 집착하기보다, 관계와 평화의 가치를 함께 따져 보세요.",
    shortMeaningReversed: "불필요한 대립은 멈추고, 배울 점을 찾아 앞으로 나아가세요.",
    themes: ["사고","결정","갈등"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "swords-06",
    slug: "six-of-swords",
    nameEn: "Six of Swords",
    nameKo: "검 6",
    arcana: "minor",
    suit: "swords",
    number: 6,
    keywordsUpright: ["전환","이동","회복"],
    keywordsReversed: ["저항","미완","불안"],
    shortMeaningUpright: "어려운 상황을 벗어나면 더 나은 환경으로 옮겨갈 수 있습니다.",
    shortMeaningReversed: "변화를 두려워하기보다, 필요한 준비를 차분히 갖추세요.",
    themes: ["사고","결정","갈등"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "swords-07",
    slug: "seven-of-swords",
    nameEn: "Seven of Swords",
    nameKo: "검 7",
    arcana: "minor",
    suit: "swords",
    number: 7,
    keywordsUpright: ["전략","기민","독립"],
    keywordsReversed: ["기만","불안","회피"],
    shortMeaningUpright: "지혜로운 계획과 유연한 행동이 복잡한 문제를 풀어 줍니다.",
    shortMeaningReversed: "지름길만 찾지 말고, 정직한 방법으로 신뢰를 회복하세요.",
    themes: ["사고","결정","갈등"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "swords-08",
    slug: "eight-of-swords",
    nameEn: "Eight of Swords",
    nameKo: "검 8",
    arcana: "minor",
    suit: "swords",
    number: 8,
    keywordsUpright: ["제한","두려움","속박"],
    keywordsReversed: ["해방","자각","선택"],
    shortMeaningUpright: "스스로 만든 걱정을 알아차리면 한 걸음씩 벗어날 수 있습니다.",
    shortMeaningReversed: "도움을 요청하고, 작은 선택부터 자유를 되찾아 보세요.",
    themes: ["사고","결정","갈등"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "swords-09",
    slug: "nine-of-swords",
    nameEn: "Nine of Swords",
    nameKo: "검 9",
    arcana: "minor",
    suit: "swords",
    number: 9,
    keywordsUpright: ["불안","걱정","스트레스"],
    keywordsReversed: ["희망","회복","지지"],
    shortMeaningUpright: "걱정이 크더라도 하나씩 나누면 마음이 조금씩 가벼워집니다.",
    shortMeaningReversed: "최악의 상상에 매달리지 말고, 확인 가능한 사실부터 정리하세요.",
    themes: ["사고","결정","갈등"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "swords-10",
    slug: "ten-of-swords",
    nameEn: "Ten of Swords",
    nameKo: "검 10",
    arcana: "minor",
    suit: "swords",
    number: 10,
    keywordsUpright: ["끝","부담","전환"],
    keywordsReversed: ["회복","해방","새 시작"],
    shortMeaningUpright: "무거운 생각의 고리를 놓으면 새로운 가능성이 열립니다.",
    shortMeaningReversed: "끝을 두려워하지 말고, 필요한 마무리 후 쉬어 가세요.",
    themes: ["사고","결정","갈등"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "swords-11",
    slug: "page-of-swords",
    nameEn: "Page of Swords",
    nameKo: "검 시종",
    arcana: "minor",
    suit: "swords",
    number: 11,
    keywordsUpright: ["호기심","아이디어","학습"],
    keywordsReversed: ["험담","산만","미숙"],
    shortMeaningUpright: "새로운 관점과 질문이 문제 해결의 실마리가 될 수 있습니다.",
    shortMeaningReversed: "확인되지 않은 말에 휘둘리지 말고, 사실을 차분히 검증하세요.",
    themes: ["사고","결정","갈등"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "swords-12",
    slug: "knight-of-swords",
    nameEn: "Knight of Swords",
    nameKo: "검 기사",
    arcana: "minor",
    suit: "swords",
    number: 12,
    keywordsUpright: ["결단","추진","열정"],
    keywordsReversed: ["충동","공격","조급"],
    shortMeaningUpright: "빠른 판단과 실행이 필요할 때, 목표를 분명히 하고 나아가세요.",
    shortMeaningReversed: "말과 행동의 날카로움을 줄이고, 상대의 입장도 함께 들어 보세요.",
    themes: ["사고","결정","갈등"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "swords-13",
    slug: "queen-of-swords",
    nameEn: "Queen of Swords",
    nameKo: "검 여왕",
    arcana: "minor",
    suit: "swords",
    number: 13,
    keywordsUpright: ["명료함","독립","직관"],
    keywordsReversed: ["냉정","고립","엄격"],
    shortMeaningUpright: "차분한 판단력으로 복잡한 상황의 중심을 잡을 수 있습니다.",
    shortMeaningReversed: "지나친 완벽주의보다 따뜻한 소통으로 균형을 찾으세요.",
    themes: ["사고","결정","갈등"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "swords-14",
    slug: "king-of-swords",
    nameEn: "King of Swords",
    nameKo: "검 왕",
    arcana: "minor",
    suit: "swords",
    number: 14,
    keywordsUpright: ["지성","권위","진실"],
    keywordsReversed: ["냉정","독단","경직"],
    shortMeaningUpright: "논리와 공정함으로 이끌면 신뢰받는 결정을 내릴 수 있습니다.",
    shortMeaningReversed: "원칙만 앞세우지 말고, 사람의 마음도 함께 헤아리세요.",
    themes: ["사고","결정","갈등"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "pentacles-01",
    slug: "ace-of-pentacles",
    nameEn: "Ace of Pentacles",
    nameKo: "펜타클 에이스",
    arcana: "minor",
    suit: "pentacles",
    number: 1,
    keywordsUpright: ["기회","재능","시작"],
    keywordsReversed: ["기회 놓침","계획 부족","불안"],
    shortMeaningUpright: "작은 실용적 기회를 붙잡으면 물질적 기반이 차곡차곡 쌓입니다.",
    shortMeaningReversed: "완벽한 타이밍을 기다리기보다, 작은 투자부터 시작하세요.",
    themes: ["현실","재물","건강"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "pentacles-02",
    slug: "two-of-pentacles",
    nameEn: "Two of Pentacles",
    nameKo: "펜타클 2",
    arcana: "minor",
    suit: "pentacles",
    number: 2,
    keywordsUpright: ["균형","조율","유연"],
    keywordsReversed: ["불균형","스트레스","우왕좌왕"],
    shortMeaningUpright: "여러 일을 유연하게 조절하면 안정적인 흐름을 유지할 수 있습니다.",
    shortMeaningReversed: "모든 것을 혼자 맞추려 하지 말고, 우선순위를 다시 정하세요.",
    themes: ["현실","재물","건강"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "pentacles-03",
    slug: "three-of-pentacles",
    nameEn: "Three of Pentacles",
    nameKo: "펜타클 3",
    arcana: "minor",
    suit: "pentacles",
    number: 3,
    keywordsUpright: ["협력","기술","성장"],
    keywordsReversed: ["미숙","소통 부족","지연"],
    shortMeaningUpright: "함께 만들어 가면 실력과 결과 모두 단단해집니다.",
    shortMeaningReversed: "피드백을 받아들이고, 기본기를 다지며 차근차근 나아가세요.",
    themes: ["현실","재물","건강"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "pentacles-04",
    slug: "four-of-pentacles",
    nameEn: "Four of Pentacles",
    nameKo: "펜타클 4",
    arcana: "minor",
    suit: "pentacles",
    number: 4,
    keywordsUpright: ["안정","저축","통제"],
    keywordsReversed: ["집착","인색","두려움"],
    shortMeaningUpright: "꾸준한 관리와 절약이 마음의 안정과 자원을 지켜 줍니다.",
    shortMeaningReversed: "지나친 통제는 줄이고, 필요한 곳에는 아낌없이 쓰세요.",
    themes: ["현실","재물","건강"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "pentacles-05",
    slug: "five-of-pentacles",
    nameEn: "Five of Pentacles",
    nameKo: "펜타클 5",
    arcana: "minor",
    suit: "pentacles",
    number: 5,
    keywordsUpright: ["어려움","결핍","불안"],
    keywordsReversed: ["지원","회복","희망"],
    shortMeaningUpright: "힘든 시기에도 도움을 구하면 실질적인 해결책이 보일 수 있습니다.",
    shortMeaningReversed: "결핍감에만 매달리지 말고, 작은 자원과 지지를 찾아보세요.",
    themes: ["현실","재물","건강"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "pentacles-06",
    slug: "six-of-pentacles",
    nameEn: "Six of Pentacles",
    nameKo: "펜타클 6",
    arcana: "minor",
    suit: "pentacles",
    number: 6,
    keywordsUpright: ["나눔","균형","관대"],
    keywordsReversed: ["불균형","의존","조건"],
    shortMeaningUpright: "주고받음의 균형을 맞추면 관계와 재정 모두 건강해집니다.",
    shortMeaningReversed: "베푸는 것과 받는 것의 균형을 점검하며, 무리한 희생은 줄이세요.",
    themes: ["현실","재물","건강"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "pentacles-07",
    slug: "seven-of-pentacles",
    nameEn: "Seven of Pentacles",
    nameKo: "펜타클 7",
    arcana: "minor",
    suit: "pentacles",
    number: 7,
    keywordsUpright: ["인내","투자","성장"],
    keywordsReversed: ["조급","실망","포기"],
    shortMeaningUpright: "꾸준한 노력이 쌓이면 시간이 지나 눈에 띄는 결실을 맺습니다.",
    shortMeaningReversed: "결과만 급하게 보려 하지 말고, 과정을 점검하며 조정하세요.",
    themes: ["현실","재물","건강"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "pentacles-08",
    slug: "eight-of-pentacles",
    nameEn: "Eight of Pentacles",
    nameKo: "펜타클 8",
    arcana: "minor",
    suit: "pentacles",
    number: 8,
    keywordsUpright: ["숙련","근면","집중"],
    keywordsReversed: ["완벽주의","지루함","번아웃"],
    shortMeaningUpright: "한 가지에 집중해 실력을 쌓으면 신뢰와 기회가 따라옵니다.",
    shortMeaningReversed: "일만 하지 말고 휴식과 의미를 함께 챙기며 균형을 맞추세요.",
    themes: ["현실","재물","건강"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "pentacles-09",
    slug: "nine-of-pentacles",
    nameEn: "Nine of Pentacles",
    nameKo: "펜타클 9",
    arcana: "minor",
    suit: "pentacles",
    number: 9,
    keywordsUpright: ["풍요","자립","안락"],
    keywordsReversed: ["과시","고립","불안"],
    shortMeaningUpright: "노력의 결실을 누리며, 스스로의 성취를 차분히 인정하세요.",
    shortMeaningReversed: "물질적 안정만으로는 부족할 수 있으니, 관계와 건강도 돌보세요.",
    themes: ["현실","재물","건강"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "pentacles-10",
    slug: "ten-of-pentacles",
    nameEn: "Ten of Pentacles",
    nameKo: "펜타클 10",
    arcana: "minor",
    suit: "pentacles",
    number: 10,
    keywordsUpright: ["유산","가정","안정"],
    keywordsReversed: ["재정 갈등","기대","부담"],
    shortMeaningUpright: "장기적인 기반과 가족·공동체의 지지가 든든한 울타리가 됩니다.",
    shortMeaningReversed: "물질적 안정에만 집착하지 말고, 소통으로 갈등을 풀어 가세요.",
    themes: ["현실","재물","건강"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "pentacles-11",
    slug: "page-of-pentacles",
    nameEn: "Page of Pentacles",
    nameKo: "펜타클 시종",
    arcana: "minor",
    suit: "pentacles",
    number: 11,
    keywordsUpright: ["학습","실용","새 기회"],
    keywordsReversed: ["미숙","게으름","산만"],
    shortMeaningUpright: "실용적인 배움과 작은 실천이 커리어와 재정의 씨앗이 됩니다.",
    shortMeaningReversed: "기초를 충실히 다지고, 꾸준함으로 성장의 속도를 높이세요.",
    themes: ["현실","재물","건강"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "pentacles-12",
    slug: "knight-of-pentacles",
    nameEn: "Knight of Pentacles",
    nameKo: "펜타클 기사",
    arcana: "minor",
    suit: "pentacles",
    number: 12,
    keywordsUpright: ["근면","책임","진행"],
    keywordsReversed: ["조급","완고","과로"],
    shortMeaningUpright: "성실하게 맡은 일을 해내면 신뢰와 기회가 함께 찾아옵니다.",
    shortMeaningReversed: "일만 밀어붙이지 말고, 효율과 휴식으로 지속 가능하게 가세요.",
    themes: ["현실","재물","건강"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "pentacles-13",
    slug: "queen-of-pentacles",
    nameEn: "Queen of Pentacles",
    nameKo: "펜타클 여왕",
    arcana: "minor",
    suit: "pentacles",
    number: 13,
    keywordsUpright: ["풍요","돌봄","실용"],
    keywordsReversed: ["의존","과잉","방치"],
    shortMeaningUpright: "현실적인 배려와 관리로 주변과 자신 모두 편안해질 수 있습니다.",
    shortMeaningReversed: "모든 것을 혼자 책임지려 하지 말고, 역할을 나누어 보세요.",
    themes: ["현실","재물","건강"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  },
  {
    id: "pentacles-14",
    slug: "king-of-pentacles",
    nameEn: "King of Pentacles",
    nameKo: "펜타클 왕",
    arcana: "minor",
    suit: "pentacles",
    number: 14,
    keywordsUpright: ["안정","성공","리더십"],
    keywordsReversed: ["물질 집착","경직","통제"],
    shortMeaningUpright: "경험과 책임감으로 현실적인 성과를 이끌 수 있는 시기입니다.",
    shortMeaningReversed: "성공만 추구하지 말고, 가치와 관계의 균형도 함께 지키세요.",
    themes: ["현실","재물","건강"],
    imageFrontPath: null,
    imageBackPath: "/images/tarot/card-back.svg",
  }
];

const deckById = new Map(TAROT_DECK.map((card) => [card.id, card]));
const deckBySlug = new Map(TAROT_DECK.map((card) => [card.slug, card]));

export function getCardById(id: string): TarotCardDefinition | undefined {
  return deckById.get(id);
}

export function getCardBySlug(slug: string): TarotCardDefinition | undefined {
  return deckBySlug.get(slug);
}

export function assertDeckIntegrity(): void {
  if (TAROT_DECK.length !== 78) {
    throw new Error(`Tarot deck must have 78 cards, got ${TAROT_DECK.length}`);
  }
  const majors = TAROT_DECK.filter((c) => c.arcana === "major");
  const minors = TAROT_DECK.filter((c) => c.arcana === "minor");
  if (majors.length !== 22) {
    throw new Error(`Major Arcana must be 22, got ${majors.length}`);
  }
  if (minors.length !== 56) {
    throw new Error(`Minor Arcana must be 56, got ${minors.length}`);
  }
  const ids = TAROT_DECK.map((c) => c.id);
  const unique = new Set(ids);
  if (unique.size !== ids.length) {
    throw new Error("Tarot deck contains duplicate card ids");
  }
  const slugs = TAROT_DECK.map((c) => c.slug);
  if (new Set(slugs).size !== slugs.length) {
    throw new Error("Tarot deck contains duplicate card slugs");
  }
}
